### PR TITLE
Feat/debounce websocket

### PR DESCRIPTION
**Pull request by eduardconstantin**
Added debounce function to mouse event

### CODE REVIEW

**Comment by swve** [comment]
@eduardconstantin Thanks a lot for your contribution! sorry bit hectic of a week, rest assured I'll review this asap. 

Is this contribution part of the #hacktoberfest challenge or is just a regular contribution, so that I can add the labels

**Comment by eduardconstantin** [comment]
No worries! It should be for hacktoberfest challenge

**Review by swve — CHANGES_REQUESTED** [review]
Hey @eduardconstantin, I reviewed your MR : 

- The debouncing is looking to be working 👍
- The formatting changes you did made this MR difficult to review, as I can't see clearly what changed *functionally* outside of the formatting 
- I pinned one change that is breaking the editor, the rest seems to be working. 

Just to be sure, can you please state me the changes you made as I'm afraid to have missed something because of the formatting. 

Thanks 🙏

**Comment by eduardconstantin** [comment]
Sorry, I have a formatter on save, I'll try to make another commit to revert the format

**Comment by swve** [comment]
Thanks a lot @eduardconstantin 🙏

**Review by swve — APPROVED** [review]

**Comment by swve** [comment]
Thanks a lot for your contribution @eduardconstantin, merging this and it will be available soon on the Cloud version.

**Pull request merged**
