### PR TITLE
NotFound Error page improvements

### PR DESCRIPTION
**Pull request by dhanyamd**

### CODE REVIEW

**Comment by dhanyamd** [comment]
@swve created a new PR, it doesn't contain anything unnecessary 👍

**Comment by swve** [comment]
@dhanyamd LGTM, is this for #hacktoberfest, do I need to validate something somewhere ? or is it a regular contribution ?

**Comment by dhanyamd** [comment]
yess it is for hacktoberfest! 🙌

**Comment by swve** [comment]
@dhanyamd  So it would be okay if I just merge the PR, nothing to do outside that right ?

**Comment by dhanyamd** [comment]
yess im not quite sure as this is my first time, but i read that it has to be under the label hacktoberfest-accepted or hacktoberfest 👍

**Comment by swve** [comment]
Thanks a lot for your contribution @dhanyamd, welcome back anytime if you have other ideas or contributions and join our Discord ;)

**Pull request merged**
