### PR TITLE
feat: created a custom-404 page instead of the default page

### PR DESCRIPTION
**Pull request by dhanyamd**
created a custom 404 page design instead of the default 404 that nextjs provides 

it redirects the user back to the main page through clicking the button below

Requirement for this implementation/PR : 

1. If ever the user while navigating manually through the routes, goes to a page that doesn't exist we wouldn't want to show something like the default black screen with no button to go back. something as small as this could lead to a bad user experience

Before : 

  
notfound

After: 

after2

### CODE REVIEW

**Comment by dhanyamd** [comment]
@swve what do you think about this 👍

**Comment by swve** [comment]
Hey @dhanyamd, this looks clean here is my review : 

- Can you experiment with the gray background to make it lighter, I feel like this would follow better the app design style. 
- Add a LearnHouse logo on top of the 404! (centered) for a more branded experience. 
- Remove the changes in the pnpm package files and npm as they're not the subject of this PR ^^ 

Thanks a lot for your contribution 🫡

**Comment by dhanyamd** [comment]
@swve is this ok? :)

**Comment by swve** [comment]
@dhanyamd Yes it looks great, we can go with that!

**Comment by dhanyamd** [comment]
it's done! 👍

**Comment by swve** [comment]
Thanks, LGTM you just forgot to : 
- Remove the changes in the pnpm package files and npm and dockerignore as they're not the subject of this PR ^^

**Pull request closed without merging**
