### PR TITLE
fixing the responsiveness across all devices for Dashboard

### PR DESCRIPTION
**Pull request by dhanyamd**
made the dashboard site that is http://localhost/dash/user-account/settings/general responsive and fit across all smaller devices 

Before :
beforedash

beforedash2

After : 

dash1

dash2

dah3

really hope this works! it worked perfectly on mine 👍

### CODE REVIEW

**Comment by swve** [comment]
Hey @dhanyamd thanks for your MR, I reckon the dashboard isn't responsive yet, but this is not how I see it can be fixed, as you can see on the "After" previews, the design of the dashboard is broken and you loose the ability to scroll inside of dashboard pages, also I mean even if we make the dashboard usable that way that would still be unresponsive and not a great experience. 

The dashboard need a greater redesign for the mobile version: the menu for example could be moved to bottom to save some space for navigation and every page would have to be redesigned to be responsive, unfortunately didn't have much time to work on this or take a decision on how to do it properly. 

This being said, I'll take time to design this soon and see what we can do and I'll be tagging you if you want to work on it, what do you think @dhanyamd ?

**Comment by dhanyamd** [comment]
yes sure i'll try my best to help! but i couldn't access the dashboard route in localhost:3000 so had to manually inspect it and made changes in the code 😅

**Comment by swve** [comment]
@dhanyamd you mean you can't find the code responsible for the dashboard route ?

**Comment by dhanyamd** [comment]
noo i mean i can access 'localhost' but when i run the app in localhost:3000 and navigate to localhost:3000/dash i get this 

err

idk if im missing something or im doing something totally wrong 🤔

**Comment by swve** [comment]
Oh, I would say a misconfig somewhere, can you show some network logs ?

**Comment by dhanyamd** [comment]
fail

f2

**Comment by swve** [comment]
@dhanyamd there is an issue with the backend, refer to https://docs.learnhouse.app/setup-dev-environment for docs

**Comment by dhanyamd** [comment]
@swve somehow unfortunately my backend doesn't seem to run + im on windows i've tried everything since 2 days! taking help from ur discord now 😅 pls if u need any assistance with the new frontend or design do tag me would love to help! 🙌

**Pull request closed without merging**
