### PR TITLE
NextJS client side sign up URL not including using organization

### PR DESCRIPTION
**Pull request by nvrthles**
- NextJS client-side sign-up URL not using user sign-up along with the organization details. -> This creates an error on the dashboard after signing up.
- Sign-up error and success message are not cleared after clicking the button. leaving an image like the one below.
Screenshot from 2023-12-27 22-21-07

### CODE REVIEW

**Comment by swve** [comment]
Hi @nvrthles, LGTM 
Can you add the Jetbrains IDE metadata files to the gitignore (.idea files) and remove the files please thanks!

**Review by swve — CHANGES_REQUESTED** [review]
Hi @nvrthles, LGTM
Can you add the Jetbrains IDE metadata files to the gitignore (.idea files) and remove the files please thanks!

**Comment by nvrthles** [comment]
Sure will do.

**Comment by swve** [comment]
Thanks for your contribution

**Pull request merged**
